# Generated by Django 3.1.6 on 2021-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notestable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntitle', models.CharField(max_length=20)),
                ('ndesc', models.TextField(max_length=1000)),
                ('nstatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notestable',
            },
        ),
    ]
